version: "3.8"

services:
  # 1. Installing redis image
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - project_network
    restart: always
    

  # 2. Installing timescale db image
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg18
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=iicpc_hackathon
    volumes:
      - iicpc_hackathon_volume:/var/lib/postgresql
      # Mapping init.sql to automatically create tables
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project_network
    restart: always

  # 3. Building image for our go load generator
  go_load_generator:
    container_name: go_load_generator
    build: ./go_bot_generator
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - project_network
    restart: always

  # 4. Building image for our backend container
  backend:
    container_name: backend
    build: ./backend
    environment:
     # passing values of environment variables
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - GRPC_SERVER_URL=${GRPC_SERVER_URL}
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - timescaledb
      - go_load_generator
    volumes:
      # Allowing Nodejs server to create containers
      - /var/run/docker.sock:/var/run/docker.sock
      # creating volume for storing the trading engine file in my sytem so that docker engine can find it and run it
      - trading_engine_volume:/app/uploads
    networks:
      - project_network

  # 5. Building the image for frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        # Frontend STILL uses 'args' because Vite bakes these into the HTML!
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_LEADERBOARD_URL=${VITE_LEADERBOARD_URL}
        - VITE_UPLOAD_URL=${VITE_UPLOAD_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - project_network

# 6. declaring volume for our timescaledb container
volumes:
  iicpc_hackathon_volume:
   name: iicpc_hackathon_volume
  trading_engine_volume:
   name: trading_engine_volume

# 7. creating custom bridge network for connecting our containers
networks:
  project_network:
    name: project_network  
    driver: bridge
