version: "3.8"

services:
  # 1. Installing redis image
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - project_network
    restart: always

  # 2. Installing timescale db image, mapping volumes and passing environment variables
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg18
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=iicpc_hackathon
    volumes:
      - iicpc_hackathon_volume:/var/lib/postgresql
      # Mapping init.sql to our container to automatically create tables
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project_network
    restart: always

  # 3. Building image for our go load generator
  go_load_generator:
    container_name: go_load_generator
    build: ./go_bot_generator
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - project_network
    restart: always

  # 4. Building image for our backend container
  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      # passing values of environment variables
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - GRPC_SERVER_URL=${GRPC_SERVER_URL}
    depends_on:
      - redis
      - timescaledb
      - go_load_generator
    volumes:
      # Allowing Nodejs server to create containers for contestant's trading engine
      - /var/run/docker.sock:/var/run/docker.sock
      # creating volume for storing the trading engine file
      - trading_engine_volume:/app/uploads
    networks:
      - project_network
  
  # 5. Creating caddy container
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - project_network
    depends_on:
      - backend

# 6. Declaring volumes
volumes:
  iicpc_hackathon_volume:
    name: iicpc_hackathon_volume
  trading_engine_volume:
    name: trading_engine_volume
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

# 7. Creating custom bridge network for connecting our containers
networks:
  project_network:
    name: project_network  
    driver: bridge